# Generated by Django 5.1.4 on 2024-12-23 22:05

import vacantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vacante', models.CharField(default=vacantes.models.generate_unique_codigo, max_length=50, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('Sin asignar', 'Sin asignar'), ('Administración', 'Administración'), ('Finanzas', 'Finanzas'), ('Tecnología', 'Tecnología'), ('Recursos Humanos', 'Recursos Humanos'), ('Ventas', 'Ventas')], default='Sin asignar', max_length=100)),
                ('numero_puestos', models.IntegerField(blank=True, default=1, null=True)),
                ('modalidad_trabajo', models.CharField(choices=[('Presencial', 'Presencial'), ('Remoto', 'Remoto'), ('Híbrido', 'Híbrido')], max_length=50)),
                ('tipo_contrato', models.CharField(choices=[('Indefinido', 'Indefinido'), ('Temporal', 'Temporal'), ('Prácticas', 'Prácticas'), ('Freelance', 'Freelance')], max_length=50)),
                ('jornada_trabajo', models.CharField(choices=[('Tiempo completo', 'Tiempo completo'), ('Medio tiempo', 'Medio tiempo'), ('Por horas', 'Por horas')], max_length=50)),
                ('descripcion_vacante', models.TextField(max_length=6000)),
                ('tiempo_experiencia', models.CharField(choices=[('Sin experiencia', 'Sin experiencia'), ('1 año', '1 año'), ('2 años', '2 años'), ('3 años o más', '3 años o más')], max_length=50)),
                ('nivel_estudios', models.CharField(choices=[('Secundaria', 'Secundaria'), ('Técnico', 'Técnico'), ('Tecnólogo', 'Tecnólogo'), ('Profesional', 'Profesional'), ('Postgrado', 'Postgrado')], max_length=50)),
                ('departamento', models.CharField(choices=[('Sin asignar', 'Sin asignar'), ('Antioquia', 'Antioquia'), ('Bogotá', 'Bogotá'), ('Valle del Cauca', 'Valle del Cauca'), ('Cundinamarca', 'Cundinamarca')], default='Sin asignar', max_length=100)),
                ('ciudad', models.CharField(choices=[('Medellín', 'Medellín'), ('Bogotá', 'Bogotá'), ('Cali', 'Cali'), ('Barranquilla', 'Barranquilla')], max_length=100)),
                ('rango_salarial', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('empresa_usuaria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
            },
        ),
    ]
