# Generated by Django 5.1.4 on 2025-01-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='candidatos_registrados',
            field=models.ManyToManyField(blank=True, related_name='vacantes', to='vacantes.registrocandidato'),
        ),
    ]
