# Generated by Django 5.1.4 on 2024-12-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocandidato',
            name='vacantes',
        ),
        migrations.AddField(
            model_name='registrocandidato',
            name='vacantes_disponibles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
