# Generated by Django 5.1.4 on 2025-01-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_vacante_candidatos_registrados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocandidato',
            name='fecha_feria',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrocandidato',
            name='feria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrocandidato',
            name='tecnico_seleccion',
            field=models.CharField(blank=True, choices=[('NN', 'No conoce el nombre'), ('AAM', 'Angel Andres Moyano Molano'), ('DAP', 'Diego Alejandro Parra Pinto'), ('EJC', 'Erika Julieth Cristancho Pérez')], max_length=3, null=True),
        ),
    ]
