# Generated by Django 5.1.4 on 2025-01-14 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0003_alter_registrocandidato_fecha_feria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocandidato',
            name='fecha_feria',
            field=models.DateField(blank=True, default=datetime.date(2025, 1, 1), null=True),
        ),
    ]
