# Generated by Django 5.1.4 on 2025-01-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0004_alter_registrocandidato_fecha_feria'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
