# Generated by Django 5.1.4 on 2025-02-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0005_vacante_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocandidato',
            name='candidato_discapacidad',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='registrocandidato',
            name='registrado_en_sise',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='registrocandidato',
            name='tecnico_seleccion',
            field=models.CharField(blank=True, choices=[('NN', 'No conoce el nombre'), ('Angel Andres Moyano Molano', 'Angel Andres Moyano Molano'), ('Diego Alejandro Parra Pinto', 'Diego Alejandro Parra Pinto'), ('Erika Julieth Cristancho Pérez', 'Erika Julieth Cristancho Pérez')], max_length=30, null=True),
        ),
    ]
