# Generated by Django 4.2.3 on 2025-02-04 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacantes', '0005_vacante_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='usuario_publicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes_publicadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
