# Generated by Django 5.1.4 on 2025-02-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0006_alter_registrocandidato_candidato_discapacidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocandidato',
            name='candidato_discapacidad',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='registrocandidato',
            name='registrado_en_sise',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='registrocandidato',
            name='tecnico_seleccion',
            field=models.CharField(blank=True, choices=[('NN', 'No conoce el nombre'), ('AAM', 'Angel Andres Moyano Molano'), ('DAP', 'Diego Alejandro Parra Pinto'), ('EJC', 'Erika Julieth Cristancho Pérez')], max_length=3, null=True),
        ),
    ]
