# Generated by Django 5.1.4 on 2025-02-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0007_alter_registrocandidato_candidato_discapacidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('Medellín', 'Medellín'), ('Bogotá', 'Bogotá'), ('Cali', 'Cali'), ('Barranquilla', 'Barranquilla')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='departamento',
            field=models.CharField(blank=True, choices=[('Sin asignar', 'Sin asignar'), ('Antioquia', 'Antioquia'), ('Bogotá', 'Bogotá'), ('Valle del Cauca', 'Valle del Cauca'), ('Cundinamarca', 'Cundinamarca')], max_length=100, null=True),
        ),
    ]
