# Generated by Django 5.1.4 on 2025-02-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0009_ciudad_departamento_alter_vacante_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nombre']},
        ),
    ]
