# Generated by Django 4.2.3 on 2025-02-13 15:47

from django.db import migrations, models
import vacantes.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0010_alter_ciudad_options_alter_departamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocandidato',
            name='aspiracion_salarial',
            field=models.IntegerField(help_text='Ingrese un valor numérico mayor a 1,000,000.', validators=[vacantes.models.validar_aspiracion_salarial]),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='area',
            field=models.CharField(blank=True, choices=[('Administración', 'Administración'), ('Finanzas', 'Finanzas'), ('Tecnología', 'Tecnología'), ('Recursos Humanos', 'Recursos Humanos'), ('Ventas', 'Ventas')], max_length=100, null=True),
        ),
    ]
