# Generated by Django 4.2.3 on 2025-02-13 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacantes', '0011_alter_registrocandidato_aspiracion_salarial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='usuario_publicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
