# Generated by Django 4.2.3 on 2025-02-13 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacantes', '0012_vacante_usuario_publicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vacante',
            name='usuario_actualizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='usuario_publicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_publicadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
