# Generated by Django 4.2.3 on 2025-02-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0013_vacante_fecha_actualizacion_vacante_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
