# Generated by Django 5.1.4 on 2025-02-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0014_alter_vacante_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='rango_salarial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
