# Generated by Django 5.1.4 on 2025-02-25 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0015_alter_vacante_rango_salarial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('No visto', 'No visto'), ('Visto', 'Visto'), ('Descartado', 'Descartado')], default='No visto', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='vacantes.registrocandidato')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='vacantes.vacante')),
            ],
            options={
                'unique_together': {('candidato', 'vacante')},
            },
        ),
    ]
