# Generated by Django 5.1.4 on 2025-03-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0016_estadoaplicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocandidato',
            name='formacion_academica',
            field=models.CharField(choices=[('BASICA PRIMARIA', 'BASICA PRIMARIA'), ('BASICA SECUNDARIA', 'BASICA SECUNDARIA'), ('BACHILLER ACADEMICO', 'BACHILLER ACADEMICO'), ('ESTUDIANTE BACHILLER ACADEMICO', 'ESTUDIANTE BACHILLER ACADEMICO'), ('TECNICO LABORAL/PROFESIONAL', 'TECNICO LABORAL/PROFESIONAL'), ('ESTUDIANTE TECNICO LABORAL/PROFESIONAL', 'ESTUDIANTE TECNICO LABORAL/PROFESIONAL'), ('TECNOLOGO', 'TECNOLOGO'), ('ESTUDIANTE TECNOLOGO', 'ESTUDIANTE TECNOLOGO'), ('PROFESIONAL', 'PROFESIONAL'), ('ESTUDIANTE PROFESIONAL', 'ESTUDIANTE PROFESIONAL'), ('POSGRADO', 'POSGRADO')], max_length=40),
        ),
        migrations.AlterField(
            model_name='registrocandidato',
            name='horario_interesado',
            field=models.CharField(choices=[('TIEMPO COMPLETO', 'TIEMPO COMPLETO'), ('MEDIO TIEMPO', 'MEDIO TIEMPO'), ('FINES DE SEMANA', 'FINES DE SEMANA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registrocandidato',
            name='sexo',
            field=models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Intersexual', 'Intersexual')], max_length=16),
        ),
        migrations.AlterField(
            model_name='registrocandidato',
            name='tecnico_seleccion',
            field=models.CharField(blank=True, choices=[('No conoce el nombre', 'No conoce el nombre'), ('Angel Andres Moyano Molano', 'Angel Andres Moyano Molano'), ('Diego Alejandro Parra Pinto', 'Diego Alejandro Parra Pinto'), ('Erika Julieth Cristancho Pérez', 'Erika Julieth Cristancho Pérez')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='registrocandidato',
            name='tipo_documento',
            field=models.CharField(choices=[('CEDULA DE CIUDADANIA', 'CEDULA DE CIUDADANIA'), ('PERMISO ESPECIAL DE PERMANENCIA', 'PERMISO ESPECIAL DE PERMANENCIA'), ('TARJETA DE IDENTIDAD', 'TARJETA DE IDENTIDAD'), ('DOCUMENTO NACIONAL DE IDENTIFICACION', 'DOCUMENTO NACIONAL DE IDENTIFICACION'), ('PASAPORTE', 'PASAPORTE'), ('CEDULA DE EXTRANJERIA', 'CEDULA DE EXTRANJERIA')], max_length=50),
        ),
    ]
