# Generated by Django 5.1.4 on 2025-03-01 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0017_alter_registrocandidato_formacion_academica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocandidato',
            name='localidad_municipio',
        ),
        migrations.AddField(
            model_name='registrocandidato',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacantes.ciudad'),
        ),
        migrations.AddField(
            model_name='registrocandidato',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacantes.departamento'),
        ),
    ]
