# Generated by Django 5.1.4 on 2025-03-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0018_remove_registrocandidato_localidad_municipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocandidato',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
