# Generated by Django 5.1.4 on 2025-03-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0020_remove_registrocandidato_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocandidato',
            name='aspiracion_salarial',
            field=models.CharField(blank=True, choices=[('Menos de 1 SMMLV', 'Menos de 1 SMMLV'), ('1 a 2 SMMLV', '1 a 2 SMMLV'), ('2 a 4 SMMLV', '2 a 4 SMMLV'), ('4 a 6 SMMLV', '4 a 6 SMMLV'), ('6 a 9 SMMLV', '6 a 9 SMMLV'), ('9 a 12 SMMLV', '9 a 12 SMMLV'), ('12 a 15 SMMLV', '12 a 15 SMMLV'), ('15 a 19 SMMLV', '15 a 19 SMMLV'), ('20 SMMLV en adelante', '20 SMMLV en adelante')], help_text='Seleccione una opción de aspiración salarial.', max_length=50),
        ),
    ]
