# Generated by Django 5.1.4 on 2025-03-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0022_alter_registrocandidato_registrado_en_sise'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocandidato',
            name='semestre_grado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
