# Generated by Django 5.1.4 on 2025-04-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0022_alter_registrocandidato_registrado_en_sise'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocandidato',
            name='codigo_sise',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrocandidato',
            name='empresa_sise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrocandidato',
            name='interes_practica',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='registrocandidato',
            name='semestre_grado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrocandidato',
            name='tipo_feria',
            field=models.CharField(blank=True, choices=[('FERIA PROPIA', 'FERIA PROPIA'), ('FERIA INVITADO', 'FERIA INVITADO'), ('FERIA MOVIL', 'FERIA MOVIL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrocandidato',
            name='tecnico_seleccion',
            field=models.CharField(blank=True, choices=[('Diego Alejandro Parra Pinto', 'Diego Alejandro Parra Pinto'), ('Jony Edilberto Chisaba Rojas', 'Jony Edilberto Chisaba Rojas'), ('Jose Luis Gamez Torres', 'Jose Luis Gamez Torres'), ('Jully Andrea Galindo Fonseca', 'Jully Andrea Galindo Fonseca'), ('Maria Alejandra Moreno Pedraza', 'Maria Alejandra Moreno Pedraza'), ('Sergio Daniel García Donado', 'Sergio Daniel García Donado'), ('Steven Alejandro Arevalo Benitez', 'Steven Alejandro Arevalo Benitez'), ('Victor De Jesus Fagua Cogollo', 'Victor De Jesus Fagua Cogollo'), ('Yennifer Alexandra Ruiz', 'Yennifer Alexandra Ruiz'), ('Yesica Natalia Lemos Lemos', 'Yesica Natalia Lemos Lemos')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='area',
            field=models.CharField(blank=True, choices=[('Administración y Gestión', 'Administración y Gestión'), ('Finanzas y Contabilidad', 'Finanzas y Contabilidad'), ('Tecnología e Informática', 'Tecnología e Informática'), ('Recursos Humanos', 'Recursos Humanos'), ('Ventas y Comercial', 'Ventas y Comercial'), ('Atención al Cliente y Servicios', 'Atención al Cliente y Servicios'), ('Marketing y Publicidad', 'Marketing y Publicidad'), ('Logística y Transporte', 'Logística y Transporte'), ('Logística y Bodega', 'Logística y Bodega'), ('Producción y Manufactura', 'Producción y Manufactura'), ('Ingeniería y Construcción', 'Ingeniería y Construcción'), ('Salud y Bienestar', 'Salud y Bienestar'), ('Educación y Formación', 'Educación y Formación'), ('Legal y Asesoría', 'Legal y Asesoría'), ('Hostelería y Turismo', 'Hostelería y Turismo'), ('Arte, Cultura y Entretenimiento', 'Arte, Cultura y Entretenimiento'), ('Medio Ambiente y Energía', 'Medio Ambiente y Energía'), ('Ciencia e Investigación', 'Ciencia e Investigación'), ('Seguridad y Defensa', 'Seguridad y Defensa'), ('Servicios Generales', 'Servicios Generales')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='nivel_estudios',
            field=models.CharField(choices=[('No Requiere', 'No Requiere'), ('Primaria', 'Primaria'), ('Bachiller Básico (Hasta 9°)', 'Bachiller Básico (Hasta 9°)'), ('Bachiller', 'Bachiller'), ('Técnico', 'Técnico'), ('Tecnólogo', 'Tecnólogo'), ('Profesional', 'Profesional'), ('Postgrado', 'Postgrado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='tiempo_experiencia',
            field=models.CharField(choices=[('Sin experiencia', 'Sin experiencia'), ('Menos de 1 año', 'Menos de 1 año'), ('1 año', '1 año'), ('2 años', '2 años'), ('3 años o más', '3 años o más')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='tipo_contrato',
            field=models.CharField(choices=[('Indefinido', 'Indefinido'), ('Fijo', 'Fijo'), ('Obra o Labor', 'Obra o Labor'), ('Prácticas', 'Prácticas'), ('Aprendizaje', 'Aprendizaje'), ('Prestación de Servicios', 'Prestación de Servicios')], max_length=50),
        ),
    ]
