# Generated by Django 5.1.4 on 2025-04-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0023_registrocandidato_codigo_sise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocandidato',
            name='cargo_sise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
