# Generated by Django 4.2.3 on 2025-04-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0024_registrocandidato_cargo_sise'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='citacion_convocatoria',
            field=models.TextField(blank=True, help_text='Solo se diligencia si la vacante es de tipo Convocatoria', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='tipo_vacante',
            field=models.CharField(choices=[('Tradicional', 'Tradicional'), ('Convocatoria', 'Convocatoria')], default='Tradicional', max_length=20),
        ),
    ]
