# Generated by Django 5.1.4 on 2025-06-14 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0025_vacante_citacion_convocatoria_vacante_tipo_vacante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocandidato',
            name='fecha_feria',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='registrocandidato',
            name='tecnico_seleccion',
            field=models.CharField(blank=True, choices=[('Diego Alejandro Parra Pinto', 'Diego Alejandro Parra Pinto'), ('Jony Edilberto Chisaba Rojas', 'Jony Edilberto Chisaba Rojas'), ('Jose Luis Gamez Torres', 'Jose Luis Gamez Torres'), ('Jully Andrea Galindo Fonseca', 'Jully Andrea Galindo Fonseca'), ('Maria Alejandra Moreno Pedraza', 'Maria Alejandra Moreno Pedraza'), ('Sergio Daniel García Donado', 'Sergio Daniel García Donado'), ('Steven Alejandro Arevalo Benitez', 'Steven Alejandro Arevalo Benitez'), ('Victor De Jesus Fagua Cogollo', 'Victor De Jesus Fagua Cogollo'), ('Yennifer Alexandra Ruiz', 'Yennifer Alexandra Ruiz'), ('Erika Julieth Cristancho Pérez', 'Erika Julieth Cristancho Pérez'), ('Gabriela Alejandra Milanes Sierra', 'Gabriela Alejandra Milanes Sierra'), ('Rosa Milena Pinilla Aldana', 'Rosa Milena Pinilla Aldana'), ('Yesica Natalia Lemos Lemos', 'Yesica Natalia Lemos Lemos')], max_length=40, null=True),
        ),
    ]
